name: footanal2
channels:
- conda-forge
- anaconda
- pytorch
dependencies:
- matplotlib>=3.2.2
- numpy>=1.18.5
- opencv>=4.1.2
- Pillow
- PyYAML>=5.3.1
- scipy>=1.4.1
- pytorch==1.9.1
- torchvision==0.10.1
- tqdm>=4.41.0
- scikit-learn
- seaborn>=0.11.0
- pandas
- pyflann